### ISSUE TITLE
eth_call

### ISSUE THREAD

**Issue by rgarc** [category-labs/monad-bft#602]
eth_call

**Comment by tongzhi1998** [comment]
TODOs on the execution end:
1. If there is validation error, currently the code returns `evmc_result{.status_code = EVMC_FAILURE}`, but should be more specific?
2. `trie_db_path` is currently just one path, but should be a vector of paths.

**Comment by rgarc** [comment]
Basic `eth_call` functionality is already completed. However, we are adding support for state overrides to consider this feature complete.

tracking PR https://github.com/monad-crypto/monad-bft/pull/803
